USE [master]
GO

/****** Object:  Database [WebApiDB]    Script Date: 17-8-2021 08:43:11 ******/
DROP DATABASE [WebApiDB]
GO

/****** Object:  Database [WebApiDB]    Script Date: 17-8-2021 08:43:11 ******/
CREATE DATABASE [WebApiDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebApiDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebApiDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebApiDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebApiDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebApiDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebApiDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebApiDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebApiDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebApiDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebApiDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebApiDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebApiDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebApiDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebApiDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebApiDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebApiDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebApiDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebApiDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebApiDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebApiDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebApiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebApiDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebApiDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebApiDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebApiDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebApiDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebApiDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebApiDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WebApiDB] SET  MULTI_USER 
GO

ALTER DATABASE [WebApiDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebApiDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebApiDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebApiDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebApiDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebApiDB] SET QUERY_STORE = OFF
GO

USE [WebApiDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [WebApiDB] SET  READ_WRITE 
GO

